### ISSUE TITLE
Command for short rest roll

### ISSUE THREAD

**Issue by sergebruni** [satanas/DnDCompanionBot#3]

**Comment by satanas** [comment]
The command should calculate the dice notation for the roll using the formula: `{level}d{dice}` where:
* level = ['character']['classes'][0]['level']
* dice = ['character']['classes'][0]['definition']['hitDice']

And validating the number of hit dice used with: ['character']['classes'][0]['hitDiceUsed']

**Comment by satanas** [comment]
Implemented in https://github.com/satanas/DnDCompanionBot/pull/13
